micronaut:
  application:
    name: iceberg
  server:
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: ["classpath:public"]
  http:
    client:
      read-timeout: